"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-08-22 17:01:09.547720

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('principles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_licence', sa.String(length=64), nullable=True),
    sa.Column('extraction', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_licence', sa.String(length=64), nullable=True),
    sa.Column('extraction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'jurisdiction_id', name='uq_act_title_juris')
    )
    op.create_index(op.f('ix_acts_short_name'), 'acts', ['short_name'], unique=False)
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('parent_court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['parent_court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('act_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('in_force_from', sa.Date(), nullable=True),
    sa.Column('in_force_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('neutral_citation', sa.String(length=64), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_licence', sa.String(length=64), nullable=True),
    sa.Column('extraction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neutral_citation')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_type', sa.String(length=16), nullable=False),
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('dst_type', sa.String(length=16), nullable=False),
    sa.Column('dst_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('treatment', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('extraction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_type', 'src_id', 'dst_type', 'dst_id', 'kind', name='uq_edge')
    )
    op.create_index('ix_edges_dst', 'edges', ['dst_type', 'dst_id'], unique=False)
    op.create_index('ix_edges_src', 'edges', ['src_type', 'src_id'], unique=False)
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('judges', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_version_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_provision_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['act_version_id'], ['act_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_provision_id'], ['provisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_version_id', 'identifier', name='uq_provision_ident')
    )
    op.create_index('ix_provisions_tsv', 'provisions', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judgment_id', 'number', name='uq_paragraph_number')
    )
    op.create_index('ix_paragraphs_tsv', 'paragraphs', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paragraphs_tsv', table_name='paragraphs', postgresql_using='gin')
    op.drop_table('paragraphs')
    op.drop_index('ix_provisions_tsv', table_name='provisions', postgresql_using='gin')
    op.drop_table('provisions')
    op.drop_table('judgments')
    op.drop_index('ix_edges_src', table_name='edges')
    op.drop_index('ix_edges_dst', table_name='edges')
    op.drop_table('edges')
    op.drop_table('cases')
    op.drop_table('act_versions')
    op.drop_table('courts')
    op.drop_index(op.f('ix_acts_short_name'), table_name='acts')
    op.drop_table('acts')
    op.drop_table('principles')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
